### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by aliburchard**
I _think_ this will fix the casing on the broken jpgs. Looks like it's a JPG vs jpg case issue. I've tweaked my git config file and also used git mv so that the changes should translate. It's a bit hard to test because all the files work locally, it's just a matter of getting the changes up online...

### CODE REVIEW

**Comment by srallen** [comment]
Getting a 404 for the zebra image. File name is `zebra-featured.jpg` so this line needs to be updated to match: https://github.com/zooniverse/wildcam-gorongosa/blob/cleaning/app/lib/field-guide-content/zebra.coffee#L8

Honey Badger is still broken for me, but I don't get a 404.

**Comment by srallen** [comment]
Oh I see you just fixed zebra. :+1:

**Comment by aliburchard** [comment]
:) yeah, i keep running into confusing things trying to rename locally and get those files tracked...

**Comment by aliburchard** [comment]
okay, try #2, since the original renames seemed to not work.

**Comment by srallen** [comment]
Zebra is working for me now, but not honey badger. I'm wondering if the issue is the image file itself. Does it render for you locally?

Yeah, it doesn't even render in browser if I open the file directly in finder using Open with... It works in Preview though.

**Comment by srallen** [comment]
I re-saved that file as png and updated the honey_badger.coffee file to use that and it now works for me. My guess is that there's something wrong with that jpg. Would you like me to push up those changes?

**Comment by aliburchard** [comment]
awesome. happy to push your changes :).

**Pull request merged**
