### PR TITLE
more liberal access token match

### PR DESCRIPTION
**Pull request by camallen**
match the new access_token format

### CODE REVIEW

**Comment by marten** [comment]
It can also contain underscores. It's [this set](https://tools.ietf.org/html/rfc4648#section-5) plus `.` between the sections.

**Comment by camallen** [comment]
cheers - might want to update [talk api too](https://github.com/zooniverse/Talk-Api/commit/0749128eff732f6d761acdc0523143933066a2ea)..

**Comment by camallen** [comment]
the `\w` will catch the underscores https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by shaunanoordin** [comment]
Deployed to https://wildcamgorongosa.org at 11:10 6 Jul 2016 and successfully confirmed that...
- Classifications can be made while not signed in
- Users can sign in
- Classifications can be made while signed in

on...
- FF47/Chrome51/Safari9+OSX

Note that any IE11/Edge issues are separate, and are addressed in #221

**Pull request merged**
