### PR TITLE
Add an "Already Seen" banner for previously viewed Subjects.

### LINKED ISSUE #230: Display "already seen" and "retired" banners
The interface doesn't display already seen (and presumably, retired) banners. This is especially problematic for assignments that only have a few images, as students can keep classifying repeatedly on the same subjects.

### PR DESCRIPTION
**Pull request by shaunanoordin**
Fixes #230 
- When a user views a subject that the user has already seen, they'll see a banner that says "Already Seen"

screen shot 2016-08-09 at 17 36 59

@srallen, could you please review this PR? Thank you!

### CODE REVIEW

**Comment by srallen** [comment]
@shaunanoordin If this is urgent, then please reassign to someone else to review. I'll be mostly unavailable for the rest of the week.

**Comment by shaunanoordin** [comment]
Understood, thank you for the quick response, Sarah. @rogerhutchings, can you please help review this PR?

**Comment by eatyourgreens** [comment]
Looks good to me.

**Comment by simoneduca** [comment]
@shaunanoordin rog's on holiday reassign to Jim please.

**Comment by eatyourgreens** [comment]
Oh, in that case…

**Pull request merged**
