### PR TITLE
Change API host to zooniverse.org

### LINKED ISSUE #184: Unable to sing-in with separate account
If I log out and then click sign-in, it signs me back in with the same account instead of giving me the option to choose. 

I was logged in to PFE with a separate account, but it didn't allow me to sign into WildCam with that account. Just signed me in with the last  account I had signed in with.

### PR DESCRIPTION
**Pull request by chrissnyder**
Closes #184

### CODE REVIEW

**Comment by camallen** [comment]
Ok - my suggestion to solve this doesn't work since it's using an oauth workflow via the panoptes.zooniverse.org server. I've been working on something to sign the user out properly...hope to have something soon.

**Comment by chrissnyder** [comment]
This should still wait on the CORS updates yea?

**Comment by camallen** [comment]
It won't work till i get them deployed no but it will work as it did before (remove the user api token) but just 404 on the delete session. Does merging here auto deploy?

**Comment by camallen** [comment]
@chrissnyder dependencies are go, this should be good to go to.

**Comment by chrissnyder** [comment]
Cool, let's give it a whirl.

**Comment by chrissnyder** [comment]
Looks to work fine here.

**Pull request merged**
